version: 2.1

jobs:

  audit:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: NPM Audit Started
          command: npm audit    

  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Build Step Started
          command: echo "Build Step Called"

workflows:

  version: 2

  build:
    jobs:
      - audit:
          filters:
            branches:
              ignore:
                - develop

  build_develop_branch:
    jobs:
      - build
      - audit:
          filters:
            branches:
              only: develop
