version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo $CIRCLE_COMPARE_URL
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Deploy Will Run"

workflows:

  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
