version: 2.1

jobs:

  build:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt -y install awscli
      # options multiline run commands
      # > 
      - run: >
          echo "this is a test of a
          multiline string"
      # the command below fails
      # - run: >
      #     aws cloudformation deploy --stack-name cloudavail-s3
      #     --template-file ./ops/cloudavail-s3.yaml
      #     --parameter-overrides BucketName=cloudavail-s3
      #       Environment=test
      #     --no-fail-on-empty-changeset
      - run: |
          aws cloudformation deploy --stack-name cloudavail-s3 \
          --template-file ./ops/cloudavail-s3.yaml \
          --parameter-overrides BucketName=cloudavail-s3 \
                                Environment=test \
          --no-fail-on-empty-changeset

workflows:

  version: 2

  build_and_deploy:
    jobs:
      - build:
          context: test
