version: 2.1

parameters:
  trigger:
    type: boolean
    default: true
  package01:
    type: boolean
    default: false
  package02:
    type: boolean
    default: false


jobs:

  trigger-workflows:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package:
        type: string
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          command: echo "Build Called for Package << parameters.package >>"


workflows:

  version: 2

  trigger-workflows:
    jobs:
      - trigger-workflows:
          filters:
            branches:
              only:
                - master
          context:
            - test

  package01:
    when: << pipeline.parameters.package01 >>
    jobs:
      - build:
          package: package01

  package02:
    when: << pipeline.parameters.package02 >>
    jobs:
      - build:
          package: package02
