# run = comprised of multiple jobs
# job = must either:
## contain a job named "build"
## must be a workflow
# workflow = can run jobs in parallel
version: 2.1
jobs:
  # the "build" job is required unless you are utilizing a workflow
  build:
    # unsure if context is available here
    # how to choose an executor type?
    # https://circleci.com/docs/2.0/executor-types/
    docker:
      # how to choose a docker image?
      # https://hub.docker.com/u/circleci
      # https://circleci.com/docs/2.0/circleci-images/
      # in this case, I'm going to utilize a docker alpine image
      - image: alpine:latest
    steps:
      # list of possible steps are here: https://circleci.com/docs/2.0/configuration-reference/#steps
      - run:
          name: Hello World
          command: echo 'Hello World'
      - run:
          context: master
          name: Database Configuration
          command: echo "Database Host is $DB_HOSTNAME"
