version: 2.1

jobs:

  build:
    docker:
      - image: circleci/aws-ecr@6.15.0
    steps:
      - checkout
      - run: ls -la
      - run:
          name: Build Step Started
          command: echo "Build Step Called"

workflows:

  version: 2

  build_and_deploy:
    jobs:
      - build
