version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: echo $GIT_BASE_REVISION
      - run: echo $GIT_REVISION
      - run: git diff --name-only $GIT_BASE_REVISION $GIT_REVISION
    environment:
      GIT_BASE_REVISION: << pipeline.git.base_revision >>
      GIT_REVISION: <<pipeline.git.revision>>
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Deploy Will Run"

workflows:

  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
