version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
            if [ "$CIRCLE_BRANCH" = "conditional" ]; then
                circleci-agent step halt
            fi
      - run: echo "After Branch Check"
  deploy:

    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Deploy Will Run"

workflows:

  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build