# run = comprised of multiple jobs
# job = must either:
## contain a job named "build"
## must be a workflow
# workflow = can run jobs in parallel
version: 2.1
jobs:
  get_configuration:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Database Configuration
          command: echo "For Database Host is $DB_HOSTNAME"

workflows:
  # version: 2 is required
  version: 2
  build_and_deploy_prod:
    jobs:
      - get_configuration:
          context: prod
          filters:
            branches:
              only: master

  build_and_deploy_dev:
    jobs:
      - get_configuration:
          context: develop
          filters:
            branches:
              only: develop
