version: 2.1

jobs:

  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Create File
          command: echo "Build Step Called"

workflows:

  version: 2

  build:
    jobs:
      - build
