version: 2.1

jobs:

  audit:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: NPM Audit Started
          command: npm audit    

  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Build Step Started
          command: echo "Build Step Called"

workflows:

  version: 2

  build:
    jobs:
      - build
      - audit
