version: 2.1

jobs:

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

workflows:

  version: 2

  trigger-workflows:
    jobs:
      - trigger-workflows:
          filters:
            branches:
              only:
                - multiple-apps-single-repo
          context:
            - test
