version: 2.1


orbs:
  aws-ecr: circleci/aws-ecr@6.15.0

jobs:

  build:
    steps:
      - aws-ecr/build-and-push-image:
          repo: bc/paylocity-employee-management
          tag: << parameters.environment >>-${CIRCLE_SHA1}
      - run: ls -la
      - persist_to_workspace:
          path: ./ops/infra.yaml

workflows:

  version: 2

  build_and_deploy:
    jobs:
      - build

